
clc

disp([' ',num2str(min(stat_a.U)),' ',num2str(max(stat_a.U))])
disp([' ',num2str(min(stat_a.V)),' ',num2str(max(stat_a.V))])
disp([' ',num2str(min(stat_a.W)),' ',num2str(max(stat_a.W))])
disp([' ',num2str(min(stat_a.vv)),' ',num2str(max(stat_a.vv))])
disp([' ',num2str(min(stat_a.ww)),' ',num2str(max(stat_a.ww))])
disp([' ',num2str(min(stat_a.uv)),' ',num2str(max(stat_a.uv))])
disp([' ',num2str(min(stat_a.vw)),' ',num2str(max(stat_a.vw))])
disp([' ',num2str(min(stat_a.P)),' ',num2str(max(stat_a.P))])
disp([' ',num2str(min(stat_a.pp)),' ',num2str(max(stat_a.pp))])
disp([' ',num2str(min(stat_a.pppp)),' ',num2str(max(stat_a.pppp))])
disp([' ',num2str(min(stat_a.uuu)),' ',num2str(max(stat_a.uuu))])
disp([' ',num2str(min(stat_a.vvv)),' ',num2str(max(stat_a.vvv))])
disp([' ',num2str(min(stat_a.uuv)),' ',num2str(max(stat_a.uuv))])
disp([' ',num2str(min(stat_a.uuw)),' ',num2str(max(stat_a.uuw))])
disp([' ',num2str(min(stat_a.uvv)),' ',num2str(max(stat_a.uvv))])
disp([' ',num2str(min(stat_a.uww)),' ',num2str(max(stat_a.uww))])
disp([' ',num2str(min(stat_a.vww)),' ',num2str(max(stat_a.vww))])
disp([' ',num2str(min(stat_a.uvw)),' ',num2str(max(stat_a.uvw))])
disp([' ',num2str(min(stat_a.Pyy)),' ',num2str(max(stat_a.Pyy))])
disp([' ',num2str(min(stat_a.Pzz)),' ',num2str(max(stat_a.Pzz))])
disp([' ',num2str(min(stat_a.Pxy)),' ',num2str(max(stat_a.Pxy))])
disp([' ',num2str(min(stat_a.Pyz)),' ',num2str(max(stat_a.Pyz))])
disp([' ',num2str(min(stat_a.Dxx)),' ',num2str(max(stat_a.Dxx))])
disp([' ',num2str(min(stat_a.Dyy)),' ',num2str(max(stat_a.Dyy))])
disp([' ',num2str(min(stat_a.Dxy)),' ',num2str(max(stat_a.Dxy))])
disp([' ',num2str(min(stat_a.Dxz)),' ',num2str(max(stat_a.Dxz))])
disp([' ',num2str(min(stat_a.Dyz)),' ',num2str(max(stat_a.Dyz))])
disp([' ',num2str(min(stat_a.Tyy)),' ',num2str(max(stat_a.Tyy))])
disp([' ',num2str(min(stat_a.Tzz)),' ',num2str(max(stat_a.Tzz))])
disp([' ',num2str(min(stat_a.Txy)),' ',num2str(max(stat_a.Txy))])
disp([' ',num2str(min(stat_a.Tyz)),' ',num2str(max(stat_a.Tyz))])
disp([' ',num2str(min(stat_a.VDxx)),' ',num2str(max(stat_a.VDxx))])
disp([' ',num2str(min(stat_a.VDyy)),' ',num2str(max(stat_a.VDyy))])
disp([' ',num2str(min(stat_a.VDxy)),' ',num2str(max(stat_a.VDxy))])
disp([' ',num2str(min(stat_a.VDxz)),' ',num2str(max(stat_a.VDxz))])
disp([' ',num2str(min(stat_a.VDyz)),' ',num2str(max(stat_a.VDyz))])
disp([' ',num2str(min(stat_a.Piyy)),' ',num2str(max(stat_a.Piyy))])
disp([' ',num2str(min(stat_a.Pizz)),' ',num2str(max(stat_a.Pizz))])
disp([' ',num2str(min(stat_a.Pixy)),' ',num2str(max(stat_a.Pixy))])
disp([' ',num2str(min(stat_a.Piyz)),' ',num2str(max(stat_a.Piyz))])
disp([' ',num2str(min(stat_a.Cxx)),' ',num2str(max(stat_a.Cxx))])
disp([' ',num2str(min(stat_a.Cyy)),' ',num2str(max(stat_a.Cyy))])
disp([' ',num2str(min(stat_a.Cxy)),' ',num2str(max(stat_a.Cxy))])
disp([' ',num2str(min(stat_a.Cxz)),' ',num2str(max(stat_a.Cxz))])
disp([' ',num2str(min(stat_a.Cyz)),' ',num2str(max(stat_a.Cyz))])
disp([' ',num2str(min(stat_a.Dk)),' ',num2str(max(stat_a.Dk))])
disp([' ',num2str(min(stat_a.Tk)),' ',num2str(max(stat_a.Tk))])
disp([' ',num2str(min(stat_a.VDk)),' ',num2str(max(stat_a.VDk))])
disp([' ',num2str(min(stat_a.Ck)),' ',num2str(max(stat_a.Ck))])
disp([' ',num2str(min(stat_a.Resk)),' ',num2str(max(stat_a.Resk))])
disp([' ',num2str(min(stat_a.PTxx)),' ',num2str(max(stat_a.PTxx))])
disp([' ',num2str(min(stat_a.PTzz)),' ',num2str(max(stat_a.PTzz))])
disp([' ',num2str(min(stat_a.PTxy)),' ',num2str(max(stat_a.PTxy))])
disp([' ',num2str(min(stat_a.PTxz)),' ',num2str(max(stat_a.PTxz))])
disp([' ',num2str(min(stat_a.PSxx)),' ',num2str(max(stat_a.PSxx))])
disp([' ',num2str(min(stat_a.PSyy)),' ',num2str(max(stat_a.PSyy))])
disp([' ',num2str(min(stat_a.PSzz)),' ',num2str(max(stat_a.PSzz))])
disp([' ',num2str(min(stat_a.PSxz)),' ',num2str(max(stat_a.PSxz))])
disp([' ',num2str(min(stat_a.PSyz)),' ',num2str(max(stat_a.PSyz))])
disp([' ',num2str(min(stat_a.dUdx)),' ',num2str(max(stat_a.dUdx))])
disp([' ',num2str(min(stat_a.dUdz)),' ',num2str(max(stat_a.dUdz))])
disp([' ',num2str(min(stat_a.dVdx)),' ',num2str(max(stat_a.dVdx))])
disp([' ',num2str(min(stat_a.dVdy)),' ',num2str(max(stat_a.dVdy))])
disp([' ',num2str(min(stat_a.dWdx)),' ',num2str(max(stat_a.dWdx))])
disp([' ',num2str(min(stat_a.dWdy)),' ',num2str(max(stat_a.dWdy))])
disp([' ',num2str(min(stat_a.dWdz)),' ',num2str(max(stat_a.dWdz))])

disp([num2str(min(stat_a.uu)),' ',num2str(max(stat_a.uu)),' ',num2str(min(stat_b.uu)),' ',num2str(max(stat_b.uu))])
disp([num2str(min(stat_a.uw)),' ',num2str(max(stat_a.uw)),' ',num2str(min(stat_b.uw)),' ',num2str(max(stat_b.uw))])
disp([num2str(min(stat_a.ppp)),' ',num2str(max(stat_a.ppp)),' ',num2str(min(stat_b.ppp)),' ',num2str(max(stat_b.ppp))])
disp([num2str(min(stat_a.www)),' ',num2str(max(stat_a.www)),' ',num2str(min(stat_b.www)),' ',num2str(max(stat_b.www))])
disp([num2str(min(stat_a.vvw)),' ',num2str(max(stat_a.vvw)),' ',num2str(min(stat_b.vvw)),' ',num2str(max(stat_b.vvw))])
disp([num2str(min(stat_a.Pxx)),' ',num2str(max(stat_a.Pxx)),' ',num2str(min(stat_b.Pxx)),' ',num2str(max(stat_b.Pxx))])
disp([num2str(min(stat_a.Pxz)),' ',num2str(max(stat_a.Pxz)),' ',num2str(min(stat_b.Pxz)),' ',num2str(max(stat_b.Pxz))])
disp([num2str(min(stat_a.Dzz)),' ',num2str(max(stat_a.Dzz)),' ',num2str(min(stat_b.Dzz)),' ',num2str(max(stat_b.Dzz))])
disp([num2str(min(stat_a.Txx)),' ',num2str(max(stat_a.Txx)),' ',num2str(min(stat_b.Txx)),' ',num2str(max(stat_b.Txx))])
disp([num2str(min(stat_a.Txz)),' ',num2str(max(stat_a.Txz)),' ',num2str(min(stat_b.Txz)),' ',num2str(max(stat_b.Txz))])
disp([num2str(min(stat_a.VDzz)),' ',num2str(max(stat_a.VDzz)),' ',num2str(min(stat_b.VDzz)),' ',num2str(max(stat_b.VDzz))])
disp([num2str(min(stat_a.Pixx)),' ',num2str(max(stat_a.Pixx)),' ',num2str(min(stat_b.Pixx)),' ',num2str(max(stat_b.Pixx))])
disp([num2str(min(stat_a.Pixz)),' ',num2str(max(stat_a.Pixz)),' ',num2str(min(stat_b.Pixz)),' ',num2str(max(stat_b.Pixz))])
disp([num2str(min(stat_a.Czz)),' ',num2str(max(stat_a.Czz)),' ',num2str(min(stat_b.Czz)),' ',num2str(max(stat_b.Czz))])
disp([num2str(min(stat_a.Pk)),' ',num2str(max(stat_a.Pk)),' ',num2str(min(stat_b.Pk)),' ',num2str(max(stat_b.Pk))])
disp([num2str(min(stat_a.Pik)),' ',num2str(max(stat_a.Pik)),' ',num2str(min(stat_b.Pik)),' ',num2str(max(stat_b.Pik))])
disp([num2str(min(stat_a.PTyy)),' ',num2str(max(stat_a.PTyy)),' ',num2str(min(stat_b.PTyy)),' ',num2str(max(stat_b.PTyy))])
disp([num2str(min(stat_a.PTyz)),' ',num2str(max(stat_a.PTyz)),' ',num2str(min(stat_b.PTyz)),' ',num2str(max(stat_b.PTyz))])
disp([num2str(min(stat_a.PSxy)),' ',num2str(max(stat_a.PSxy)),' ',num2str(min(stat_b.PSxy)),' ',num2str(max(stat_b.PSxy))])
disp([num2str(min(stat_a.dUdy)),' ',num2str(max(stat_a.dUdy)),' ',num2str(min(stat_b.dUdy)),' ',num2str(max(stat_b.dUdy))])
disp([num2str(min(stat_a.dVdz)),' ',num2str(max(stat_a.dVdz)),' ',num2str(min(stat_b.dVdz)),' ',num2str(max(stat_b.dVdz))])

disp([' ',num2str(min(stat_b.dPdx)),' ',num2str(max(stat_b.dPdx))])
disp([' ',num2str(min(stat_b.dPdy)),' ',num2str(max(stat_b.dPdy))])
disp([' ',num2str(min(stat_b.dPdz)),' ',num2str(max(stat_b.dPdz))])
