#!/bin/bash
export CASE="duct"
export SOURCE_ROOT="/scratch/gzampino/KTH_Nek5000v17/Nek5000"
export FC="mpif77"
export CC="mpicc"
#export CFLAGS="-std=legacy -mcmodel=large"
#export FFLAGS="-std=legacy -mcmodel=large"
export CFLAGS="-std=legacy"
export FFLAGS="-std=legacy"

export PPLIST=""
export USR="frame.o frame_usr.o io_tools_block.o io_tools.o mntrlog_block.o mntrlog.o mntrtmr_block.o mntrtmr.o rprm_block.o rprm.o map2D.o stat.o stat_IO.o trip.o"

for il in "$@"
do
case $il in
	--clean)
		${SOURCE_ROOT}/bin/makenek clean
		shift
		;;
	--compile)
                ${SOURCE_ROOT}/bin/makenek ${CASE}
		shift
		;;
esac
done

